baseurl: ""

collections:
  posts:
    output: true
    permalink: /blog/:title/

exclude: [
  CNAME,
  LICENSE,
  README.md
]

paginate_path: /pages/:num/

sass:
  sass_dir: _scss
  style: compressed

timezone: Europe/Rome
