baseurl: ''

author:
  full_name: Federico Moretti
  nickname: fedtti
  email: hello@federicomoretti.it

collections:
  posts:
    output: true
    permalink: /blog/:title/

description: >-
  Software developer proficient in creating solutions using HTML, CSS, and JavaScript.

exclude: [
  CNAME,
  LICENSE,
  README.md
]

id: urn:uuid:e32f7e38-2b5c-3b84-a32e-132e12179e93 # TODO: @fedtti - Generate a new UUID automatically via Jekyll UUIDv3 Plugin (yet to be implemented).

og_description: >-
  Italian software developer who helps BPOs in digital transformation with AI by creating solutions using HTML, CSS, and JavaScript.
og_title: Federico Moretti AKA “fedtti”

pagination:
  enabled: true
  per_page: 10
  permalink: /page/:num/

plugins:
  - jekyll-paginate-v2

sass:
  sass_dir: _scss
  style: compressed

timezone: Europe/Rome

title: Federico Moretti AKA “fedtti” • Software Developer

url: https://federicomoretti.it
